references:
  workspace_root: &workspace_root
    ~/repo
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
  working_directory: *workspace_root

version: 2
jobs:
  install:
    <<: *defaults
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  build:
    <<: *defaults
    docker:
      - image: circleci/node:8.5
    steps:
      - *attach_workspace
      - run: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy_stage:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: aws s3 sync dist/ s3://acast-cdn/embed-sdk/dev

  deploy_prod:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: aws s3 sync dist/ s3://acast-cdn/embed-sdk/{{ .Environment.CIRCLE_TAG }}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - deploy_stage:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
      - approve_prod:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d{1,}\.\d{1,}\.\d{1,}/
      - deploy_prod:
          requires:
            - approve_prod
          filters:
            tags:
              only: /.*/
